import ProductsGrid from "@/features/productsList/components/ProductsGrid";
import ProductsSkeleton from "@/features/productsList/components/skeleton/ProductsSkeleton";
import WishListEmpty from "@/features/WishList/components/WishListEmpty";
const sampleProducts:any[] = [
  {
    id: 36,
    title: "Protein Powder",
    description:
      "Nutrient-packed protein powder, ideal for supplementing your diet with essential proteins.",
    category: "groceries",
    price: 19.99,
    discountPercentage: 7.59,
    rating: 4.18,
    stock: 80,
    tags: ["health supplements"],
    sku: "GRO-BRD-PRO-036",
    weight: 9,
    dimensions: { width: 9.01, height: 12.53, depth: 22.35 },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aurora Rodriguez",
        reviewerEmail: "aurora.rodriguez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Miles Stevenson",
        reviewerEmail: "miles.stevenson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 6,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "0435397154434",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/protein-powder/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp",
  },
  {
    id: 37,
    title: "Red Onions",
    description:
      "Flavorful and aromatic red onions, perfect for adding depth to your savory dishes.",
    category: "groceries",
    price: 1.99,
    discountPercentage: 9.9,
    rating: 4.2,
    stock: 82,
    tags: ["vegetables"],
    sku: "GRO-BRD-ONI-037",
    weight: 9,
    dimensions: { width: 16.01, height: 24.96, depth: 12.74 },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Evelyn Gonzalez",
        reviewerEmail: "evelyn.gonzalez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jackson Evans",
        reviewerEmail: "jackson.evans@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 8,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "4716374115631",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/red-onions/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/red-onions/thumbnail.webp",
  },
  {
    id: 38,
    title: "Rice",
    description:
      "High-quality rice, a staple for various cuisines and a versatile base for many dishes.",
    category: "groceries",
    price: 5.99,
    discountPercentage: 9.29,
    rating: 3.18,
    stock: 59,
    tags: ["grains"],
    sku: "GRO-BRD-RIC-038",
    weight: 5,
    dimensions: { width: 17.21, height: 9.88, depth: 17.16 },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Cameron Burke",
        reviewerEmail: "cameron.burke@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 20,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "7339757397015",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/product-images/groceries/rice/1.webp"],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp",
  },
  {
    id: 39,
    title: "Soft Drinks",
    description:
      "Assorted soft drinks in various flavors, perfect for refreshing beverages.",
    category: "groceries",
    price: 1.99,
    discountPercentage: 17.48,
    rating: 4.75,
    stock: 53,
    tags: ["beverages"],
    sku: "GRO-BRD-SOF-039",
    weight: 9,
    dimensions: { width: 19.75, height: 6.79, depth: 9.33 },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Zachary Lee",
        reviewerEmail: "zachary.lee@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Hannah Robinson",
        reviewerEmail: "hannah.robinson@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "2991169581178",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp",
  },
  {
    id: 40,
    title: "Strawberry",
    description:
      "Sweet and succulent strawberries, great for snacking, desserts, or blending into smoothies.",
    category: "groceries",
    price: 3.99,
    discountPercentage: 1.12,
    rating: 3.08,
    stock: 46,
    tags: ["fruits"],
    sku: "GRO-BRD-STR-040",
    weight: 1,
    dimensions: { width: 28.18, height: 21.25, depth: 28.54 },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Amelia Perez",
        reviewerEmail: "amelia.perez@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Olivia Wilson",
        reviewerEmail: "olivia.wilson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Hunter Gordon",
        reviewerEmail: "hunter.gordon@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 12,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "0792647462295",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/strawberry/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp",
  },
  {
    id: 41,
    title: "Tissue Paper Box",
    description:
      "Convenient tissue paper box for everyday use, providing soft and absorbent tissues.",
    category: "groceries",
    price: 2.49,
    discountPercentage: 13.28,
    rating: 2.69,
    stock: 86,
    tags: ["household essentials"],
    sku: "GRO-BRD-TIS-041",
    weight: 1,
    dimensions: { width: 18.75, height: 17.58, depth: 12.43 },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ariana Ross",
        reviewerEmail: "ariana.ross@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Carter Baker",
        reviewerEmail: "carter.baker@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 44,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9446468291745",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/1.webp",
      "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/2.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp",
  },
  {
    id: 42,
    title: "Water",
    description:
      "Pure and refreshing bottled water, essential for staying hydrated throughout the day.",
    category: "groceries",
    price: 0.99,
    discountPercentage: 14.92,
    rating: 4.96,
    stock: 53,
    tags: ["beverages"],
    sku: "GRO-BRD-WAT-042",
    weight: 4,
    dimensions: { width: 18.43, height: 7.4, depth: 17.79 },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jonathan Pierce",
        reviewerEmail: "jonathan.pierce@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Grayson Coleman",
        reviewerEmail: "grayson.coleman@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ethan Fletcher",
        reviewerEmail: "ethan.fletcher@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 28,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "2409829645213",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: ["https://cdn.dummyjson.com/product-images/groceries/water/1.webp"],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp",
  },
]; // Replace with actual data fetching logic
export default function WishList() {
  if (false) return <WishListEmpty />;
  return (
    <div className="py-8">
      <h4 className="font-bold mb-4">Your WishList</h4>
      {/* {isFetching && <ProductsSkeleton limit={12} viewMode="grid" />} */}

      <ProductsGrid products={sampleProducts} viewMode="grid" />
    </div>
  );
}
